server:
  port: 8080

tistory:
  blog-name: ${BLOG_NAME}
  rss-url: ${BLOG_URL}

github:
  token: ${GITHUB_TOKEN}
  name: pparkcoder
  repository: pparkcoder
  branch: main #README.md는 main 브랜치를 기준으로 읽어옴

sync:
  cron: "0 0 * * * *"
  recent-post-count: 5 # README에 보여줄 최신 글 수